<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>MLR</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="MLR_files/libs/clipboard/clipboard.min.js"></script>
<script src="MLR_files/libs/quarto-html/quarto.js"></script>
<script src="MLR_files/libs/quarto-html/popper.min.js"></script>
<script src="MLR_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="MLR_files/libs/quarto-html/anchor.min.js"></script>
<link href="MLR_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="MLR_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="MLR_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="MLR_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="MLR_files/libs/bootstrap/bootstrap-1bc8a17f135ab3d594c857e9f48e611b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">MLR</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="load-required-packages" class="level1">
<h1>Load required packages</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(RcmdrMisc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: car</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: sandwich</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="importing-data" class="level2">
<h2 class="anchored" data-anchor-id="importing-data">Importing data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>chap7data2 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"chap7data2.csv"</span>, <span class="at">sep=</span><span class="st">","</span>, <span class="at">header=</span>T)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>chap7data3 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"chap7data3.csv"</span>, <span class="at">sep=</span><span class="st">","</span>, <span class="at">header=</span>T)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(chap7data2)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(chap7data3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>#scatter plot</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plots of 'Detox' against each enzyme</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(chap7data2, <span class="fu">aes</span>(<span class="at">x =</span> Enzyme1, <span class="at">y =</span> Detox)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"Detox vs Enzyme1"</span>) <span class="sc">+</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="MLR_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(chap7data2, <span class="fu">aes</span>(<span class="at">x =</span> Enzyme2, <span class="at">y =</span> Detox)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"Detox vs Enzyme2"</span>) <span class="sc">+</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="MLR_files/figure-html/unnamed-chunk-3-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(chap7data2, <span class="fu">aes</span>(<span class="at">x =</span> Enzyme3, <span class="at">y =</span> Detox)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"Detox vs Enzyme3"</span>) <span class="sc">+</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="MLR_files/figure-html/unnamed-chunk-3-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(chap7data2, <span class="fu">aes</span>(<span class="at">x =</span> Enzyme4, <span class="at">y =</span> Detox)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"Detox vs Enzyme4"</span>) <span class="sc">+</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="MLR_files/figure-html/unnamed-chunk-3-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(chap7data2, <span class="fu">aes</span>(<span class="at">x =</span> Enzyme5, <span class="at">y =</span> Detox)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"Detox vs Enzyme5"</span>) <span class="sc">+</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="MLR_files/figure-html/unnamed-chunk-3-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>#or</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(chap7data2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="MLR_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>#or</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">scatterplotMatrix</span>(<span class="sc">~</span>Detox <span class="sc">+</span> Enzyme1 <span class="sc">+</span> Enzyme2 <span class="sc">+</span> Enzyme3 <span class="sc">+</span> Enzyme4 <span class="sc">+</span> Enzyme5,</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">reg.line =</span> lm,</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">smooth =</span> <span class="cn">FALSE</span>,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">spread =</span> <span class="cn">FALSE</span>,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">span =</span> <span class="fl">0.5</span>,</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">ellipse =</span> <span class="cn">FALSE</span>,</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">levels =</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">0.9</span>),</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>                  <span class="at">id.n =</span> <span class="dv">0</span>,</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>                  <span class="at">diagonal =</span> <span class="st">'density'</span>,</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> chap7data2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in applyDefaults(diagonal, defaults = list(method = "adaptiveDensity"),
: unnamed diag arguments, will be ignored</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "reg.line" is not
a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "spread" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "span" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "levels" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "id.n" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "reg.line" is not
a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "spread" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "span" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "levels" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "id.n" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "reg.line" is not
a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "spread" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "span" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "levels" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "id.n" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "reg.line" is not
a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "spread" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "span" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "levels" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "id.n" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "reg.line" is not
a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "spread" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "span" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "levels" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "id.n" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "reg.line" is not
a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "spread" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "span" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "levels" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "id.n" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "reg.line" is not
a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "spread" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "span" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "levels" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "id.n" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "reg.line" is not
a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "spread" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "span" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "levels" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "id.n" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "reg.line" is not
a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "spread" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "span" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "levels" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "id.n" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "reg.line" is not
a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "spread" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "span" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "levels" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "id.n" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "reg.line" is not
a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "spread" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "span" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "levels" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "id.n" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "reg.line" is not
a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "spread" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "span" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "levels" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "id.n" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "reg.line" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "spread" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "span" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "levels" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "id.n" is not a graphical parameter</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="MLR_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="interpretation" class="level2">
<h2 class="anchored" data-anchor-id="interpretation">Interpretation</h2>
<p>This document provides an interpretation of the scatterplot matrix that includes the response variable (<code>Detox</code>) and explanatory variables (<code>Enzyme1</code>, <code>Enzyme2</code>, <code>Enzyme3</code>, <code>Enzyme4</code>, and <code>Enzyme5</code>). The scatterplot matrix is used to visualize the relationships between these variables and identify potential correlations.</p>
<section id="relationships-between-detox-and-each-enzyme" class="level3">
<h3 class="anchored" data-anchor-id="relationships-between-detox-and-each-enzyme">1. Relationships Between <code>Detox</code> and Each Enzyme</h3>
<ul>
<li><p><strong><code>Detox</code> vs.&nbsp;<code>Enzyme1</code></strong>:<br>
There is a positive linear relationship, as indicated by the upward trend in the scatter plot. The regression line is slightly upward, and the points are moderately scattered around it, suggesting a moderate positive correlation.</p></li>
<li><p><strong><code>Detox</code> vs.&nbsp;<code>Enzyme2</code></strong>:<br>
The scatter plot shows a very weak relationship with a mostly horizontal regression line. The points are widely scattered without any discernible pattern, suggesting little to no linear relationship between <code>Detox</code> and <code>Enzyme2</code>.</p></li>
<li><p><strong><code>Detox</code> vs.&nbsp;<code>Enzyme3</code></strong>:<br>
The plot shows a positive linear relationship, as evidenced by the upward trend and a moderately steep regression line. Points are somewhat dispersed, but there is a noticeable trend suggesting a moderate positive correlation.</p></li>
<li><p><strong><code>Detox</code> vs.&nbsp;<code>Enzyme4</code></strong>:<br>
There appears to be a slight negative linear relationship. The regression line slopes downward, but the points are widely scattered. This suggests a weak negative correlation between <code>Detox</code> and <code>Enzyme4</code>.</p></li>
<li><p><strong><code>Detox</code> vs.&nbsp;<code>Enzyme5</code></strong>:<br>
The scatter plot indicates a weak relationship with a relatively flat regression line. The points are fairly scattered, with no clear trend, suggesting little to no linear correlation between <code>Detox</code> and <code>Enzyme5</code>.</p></li>
</ul>
</section>
<section id="relationships-among-explanatory-variables-enzyme1-to-enzyme5" class="level3">
<h3 class="anchored" data-anchor-id="relationships-among-explanatory-variables-enzyme1-to-enzyme5">2. Relationships Among Explanatory Variables (<code>Enzyme1</code> to <code>Enzyme5</code>)</h3>
<ul>
<li><p><strong><code>Enzyme1</code> vs.&nbsp;<code>Enzyme2</code></strong>:<br>
There is a noticeable positive linear relationship with an upward trend. The regression line is moderately steep, and points are clustered around it, indicating a moderate positive correlation.</p></li>
<li><p><strong><code>Enzyme1</code> vs.&nbsp;<code>Enzyme3</code>, <code>Enzyme4</code>, <code>Enzyme5</code></strong>:<br>
All these plots show relatively moderate positive linear relationships, with upward trends and points moderately clustered around the regression lines.</p></li>
<li><p><strong><code>Enzyme2</code> vs.&nbsp;<code>Enzyme3</code></strong>:<br>
The relationship appears to be non-linear, with points forming a curved pattern. This suggests a non-linear relationship between <code>Enzyme2</code> and <code>Enzyme3</code>.</p></li>
<li><p><strong><code>Enzyme2</code> vs.&nbsp;<code>Enzyme4</code>, <code>Enzyme5</code></strong>:<br>
These plots show no clear pattern, suggesting little to no linear relationship between <code>Enzyme2</code> and either <code>Enzyme4</code> or <code>Enzyme5</code>.</p></li>
<li><p><strong><code>Enzyme3</code> vs.&nbsp;<code>Enzyme4</code></strong>:<br>
There seems to be a positive relationship with an upward trend in the scatter plot, though the points are somewhat scattered, indicating a moderate positive correlation.</p></li>
<li><p><strong><code>Enzyme3</code> vs.&nbsp;<code>Enzyme5</code></strong>:<br>
Shows a weak or no discernible relationship, with the points widely scattered around a flat regression line.</p></li>
<li><p><strong><code>Enzyme4</code> vs.&nbsp;<code>Enzyme5</code></strong>:<br>
No clear relationship is observed here, as the points are scattered without any noticeable pattern.</p></li>
</ul>
</section>
<section id="diagonal-plots-density-plots" class="level3">
<h3 class="anchored" data-anchor-id="diagonal-plots-density-plots">3. Diagonal Plots (Density Plots)</h3>
<ul>
<li>The diagonal plots display the distribution of each variable. For example:
<ul>
<li><strong><code>Detox</code></strong> appears to have a somewhat skewed distribution, possibly slightly left-skewed.</li>
<li><strong><code>Enzyme1</code></strong> and <strong><code>Enzyme3</code></strong> appear to be normally distributed with slight variation.</li>
<li><strong><code>Enzyme2</code></strong> shows a highly skewed distribution with a long tail.</li>
<li><strong><code>Enzyme4</code></strong> and <strong><code>Enzyme5</code></strong> show more uniform distributions with less obvious skewness.</li>
</ul></li>
</ul>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<ul>
<li><code>Detox</code> has a moderate positive relationship with <code>Enzyme1</code> and <code>Enzyme3</code>, suggesting these enzymes might be more influential in predicting <code>Detox</code> levels.</li>
<li><code>Enzyme2</code> and <code>Enzyme5</code> appear to have little to no linear relationship with <code>Detox</code>.</li>
<li>The relationships among explanatory variables vary, with some moderate positive linear correlations (like <code>Enzyme1</code> with <code>Enzyme2</code>), and some non-linear or weak relationships.</li>
</ul>
</section>
</section>
</section>
<section id="multiple-linear-regression" class="level1">
<h1>Multiple linear regression</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb615"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb615-1"><a href="#cb615-1" aria-hidden="true" tabindex="-1"></a>chap7data2.model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Detox<span class="sc">~</span>.,<span class="at">data=</span>chap7data2)</span>
<span id="cb615-2"><a href="#cb615-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(chap7data2.model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Detox ~ ., data = chap7data2)

Residuals:
       1        2        3        4        5        6        7        8 
  2.7526  -3.0631  -0.8577  -2.1760   6.2696  21.6524 -36.4182  11.8682 
       9       10 
-19.7684  19.7406 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)
(Intercept) -87.96535  189.66881  -0.464    0.667
Enzyme1       0.17063    0.10045   1.699    0.165
Enzyme2       0.03305    0.14039   0.235    0.825
Enzyme3       0.31844    0.67350   0.473    0.661
Enzyme4       0.04325    0.13468   0.321    0.764
Enzyme5       0.72460    1.69421   0.428    0.691

Residual standard error: 26.35 on 4 degrees of freedom
Multiple R-squared:  0.798, Adjusted R-squared:  0.5455 
F-statistic: 3.161 on 5 and 4 DF,  p-value: 0.1439</code></pre>
</div>
</div>
<section id="the-allsubsets-function" class="level2">
<h2 class="anchored" data-anchor-id="the-allsubsets-function">#the allSubsets() function</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb617"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb617-1"><a href="#cb617-1" aria-hidden="true" tabindex="-1"></a>allSubsets <span class="ot">&lt;-</span> <span class="cf">function</span>(data,<span class="at">y.name=</span><span class="st">"Y"</span>,<span class="at">perf.measure=</span><span class="fu">c</span>(<span class="st">"adj.r.squared"</span>,<span class="st">"r.squared"</span>,<span class="st">"AIC"</span>,<span class="st">"perc.error"</span>)){</span>
<span id="cb617-2"><a href="#cb617-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb617-3"><a href="#cb617-3" aria-hidden="true" tabindex="-1"></a>  Cols <span class="ot">&lt;-</span> <span class="fu">names</span>(data)</span>
<span id="cb617-4"><a href="#cb617-4" aria-hidden="true" tabindex="-1"></a>  Cols <span class="ot">&lt;-</span> Cols[<span class="sc">!</span> Cols <span class="sc">%in%</span> y.name]</span>
<span id="cb617-5"><a href="#cb617-5" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">&lt;-</span> <span class="fu">length</span>(Cols)</span>
<span id="cb617-6"><a href="#cb617-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb617-7"><a href="#cb617-7" aria-hidden="true" tabindex="-1"></a>  id <span class="ot">&lt;-</span> <span class="fu">unlist</span>(</span>
<span id="cb617-8"><a href="#cb617-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">lapply</span>(<span class="dv">1</span><span class="sc">:</span>n,</span>
<span id="cb617-9"><a href="#cb617-9" aria-hidden="true" tabindex="-1"></a>           <span class="cf">function</span>(i)<span class="fu">combn</span>(<span class="dv">1</span><span class="sc">:</span>n,i,<span class="at">simplify=</span>F)</span>
<span id="cb617-10"><a href="#cb617-10" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb617-11"><a href="#cb617-11" aria-hidden="true" tabindex="-1"></a>    ,<span class="at">recursive=</span>F)</span>
<span id="cb617-12"><a href="#cb617-12" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb617-13"><a href="#cb617-13" aria-hidden="true" tabindex="-1"></a>  Formulas <span class="ot">&lt;-</span> <span class="fu">sapply</span>(id,<span class="cf">function</span>(i)</span>
<span id="cb617-14"><a href="#cb617-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">paste</span>(y.name,<span class="st">"~"</span>,<span class="fu">paste</span>(Cols[i],<span class="at">collapse=</span><span class="st">"+"</span>))</span>
<span id="cb617-15"><a href="#cb617-15" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb617-16"><a href="#cb617-16" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb617-17"><a href="#cb617-17" aria-hidden="true" tabindex="-1"></a>  result.mat <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">0</span>,<span class="at">nrow=</span><span class="fu">length</span>(Formulas),<span class="dv">6</span>)</span>
<span id="cb617-18"><a href="#cb617-18" aria-hidden="true" tabindex="-1"></a>  result.mat[,<span class="dv">1</span>] <span class="ot">&lt;-</span> Formulas</span>
<span id="cb617-19"><a href="#cb617-19" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb617-20"><a href="#cb617-20" aria-hidden="true" tabindex="-1"></a>  <span class="co">#get all adjusted R2 values</span></span>
<span id="cb617-21"><a href="#cb617-21" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(Formulas)){result.mat[i,<span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="fu">summary</span>(<span class="fu">lm</span>(<span class="fu">as.formula</span>(Formulas[i]),</span>
<span id="cb617-22"><a href="#cb617-22" aria-hidden="true" tabindex="-1"></a>                                                             <span class="at">data=</span>data))<span class="sc">$</span>adj.r.squared}</span>
<span id="cb617-23"><a href="#cb617-23" aria-hidden="true" tabindex="-1"></a>  <span class="co">#get all R2 values</span></span>
<span id="cb617-24"><a href="#cb617-24" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(Formulas)){result.mat[i,<span class="dv">3</span>] <span class="ot">&lt;-</span> <span class="fu">summary</span>(<span class="fu">lm</span>(<span class="fu">as.formula</span>(Formulas[i]),</span>
<span id="cb617-25"><a href="#cb617-25" aria-hidden="true" tabindex="-1"></a>                                                             <span class="at">data=</span>data))<span class="sc">$</span>r.squared}</span>
<span id="cb617-26"><a href="#cb617-26" aria-hidden="true" tabindex="-1"></a>  <span class="co">#get all AIC's</span></span>
<span id="cb617-27"><a href="#cb617-27" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb617-28"><a href="#cb617-28" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(Formulas)){result.mat[i,<span class="dv">4</span>] <span class="ot">&lt;-</span> <span class="fu">AIC</span>(<span class="fu">lm</span>(<span class="fu">as.formula</span>(Formulas[i]),</span>
<span id="cb617-29"><a href="#cb617-29" aria-hidden="true" tabindex="-1"></a>                                                         <span class="at">data=</span>data))}</span>
<span id="cb617-30"><a href="#cb617-30" aria-hidden="true" tabindex="-1"></a>  <span class="co">#get all sigma's</span></span>
<span id="cb617-31"><a href="#cb617-31" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb617-32"><a href="#cb617-32" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(Formulas)){result.mat[i,<span class="dv">5</span>] <span class="ot">&lt;-</span> <span class="fu">summary</span>(<span class="fu">lm</span>(<span class="fu">as.formula</span>(Formulas[i]),</span>
<span id="cb617-33"><a href="#cb617-33" aria-hidden="true" tabindex="-1"></a>                                                             <span class="at">data=</span>data))<span class="sc">$</span>sigma<span class="sc">/</span><span class="fu">mean</span>(data[,y.name])}</span>
<span id="cb617-34"><a href="#cb617-34" aria-hidden="true" tabindex="-1"></a>  <span class="co">#get all mallows cp's</span></span>
<span id="cb617-35"><a href="#cb617-35" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb617-36"><a href="#cb617-36" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(Formulas)){result.mat[i,<span class="dv">6</span>] <span class="ot">&lt;-</span> <span class="fu">mallows.cp</span>(<span class="at">data=</span>data,<span class="at">model=</span><span class="fu">lm</span>(<span class="fu">as.formula</span>(Formulas[i]),</span>
<span id="cb617-37"><a href="#cb617-37" aria-hidden="true" tabindex="-1"></a>                                                                                <span class="at">data=</span>data),<span class="at">y.name=</span>y.name)}</span>
<span id="cb617-38"><a href="#cb617-38" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb617-39"><a href="#cb617-39" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb617-40"><a href="#cb617-40" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb617-41"><a href="#cb617-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">colnames</span>(result.mat) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Model"</span>,<span class="st">"adj.r.squared"</span>,<span class="st">"r.squared"</span>,<span class="st">"AIC"</span>,<span class="st">"perc.error"</span>,<span class="st">"mallows.cp"</span>)</span>
<span id="cb617-42"><a href="#cb617-42" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb617-43"><a href="#cb617-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb617-44"><a href="#cb617-44" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb617-45"><a href="#cb617-45" aria-hidden="true" tabindex="-1"></a>  final.output <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(result.mat[<span class="fu">order</span>(result.mat[,perf.measure],<span class="at">decreasing=</span>T),])</span>
<span id="cb617-46"><a href="#cb617-46" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb617-47"><a href="#cb617-47" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(final.output)</span>
<span id="cb617-48"><a href="#cb617-48" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb617-49"><a href="#cb617-49" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="calculating-the-mallows-cp-statistic-function" class="level2">
<h2 class="anchored" data-anchor-id="calculating-the-mallows-cp-statistic-function">calculating the Mallow’s Cp statistic (function)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb618"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb618-1"><a href="#cb618-1" aria-hidden="true" tabindex="-1"></a>mallows.cp <span class="ot">&lt;-</span> <span class="cf">function</span>(data,model,y.name)</span>
<span id="cb618-2"><a href="#cb618-2" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb618-3"><a href="#cb618-3" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb618-4"><a href="#cb618-4" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(data)</span>
<span id="cb618-5"><a href="#cb618-5" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> <span class="fu">length</span>(model<span class="sc">$</span>coefficients)</span>
<span id="cb618-6"><a href="#cb618-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb618-7"><a href="#cb618-7" aria-hidden="true" tabindex="-1"></a>  mean.sq.error <span class="ot">&lt;-</span> <span class="fu">summary</span>(<span class="fu">lm</span>(<span class="fu">as.formula</span>(<span class="fu">paste</span>(y.name,<span class="st">"~."</span>)),<span class="at">data=</span>data))<span class="sc">$</span>sigma<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb618-8"><a href="#cb618-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb618-9"><a href="#cb618-9" aria-hidden="true" tabindex="-1"></a>  sse <span class="ot">&lt;-</span> <span class="fu">summary</span>(model)<span class="sc">$</span>sigma<span class="sc">^</span><span class="dv">2</span><span class="sc">*</span><span class="fu">summary</span>(model)<span class="sc">$</span>df[<span class="dv">2</span>]</span>
<span id="cb618-10"><a href="#cb618-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb618-11"><a href="#cb618-11" aria-hidden="true" tabindex="-1"></a>  cp <span class="ot">&lt;-</span> sse<span class="sc">/</span>mean.sq.error<span class="sc">-</span>(n<span class="dv">-2</span><span class="sc">*</span>p)</span>
<span id="cb618-12"><a href="#cb618-12" aria-hidden="true" tabindex="-1"></a>  cp<span class="sc">/</span><span class="dv">100</span></span>
<span id="cb618-13"><a href="#cb618-13" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="variable-selection" class="level1">
<h1>Variable selection</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb619"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb619-1"><a href="#cb619-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stepwise</span>(chap7data2.model1, <span class="at">direction=</span><span class="st">'backward/forward'</span>, <span class="at">criterion=</span><span class="st">'AIC'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Direction:  backward/forward
Criterion:  AIC 

Start:  AIC=68.27
Detox ~ Enzyme1 + Enzyme2 + Enzyme3 + Enzyme4 + Enzyme5

          Df Sum of Sq    RSS    AIC
- Enzyme2  1     38.50 2816.7 66.407
- Enzyme4  1     71.60 2849.8 66.524
- Enzyme5  1    127.05 2905.2 66.717
- Enzyme3  1    155.27 2933.4 66.813
&lt;none&gt;                 2778.2 68.270
- Enzyme1  1   2004.15 4782.3 71.701

Step:  AIC=66.41
Detox ~ Enzyme1 + Enzyme3 + Enzyme4 + Enzyme5

          Df Sum of Sq    RSS    AIC
- Enzyme3  1     130.4 2947.1 64.860
- Enzyme4  1     221.1 3037.8 65.163
&lt;none&gt;                 2816.7 66.407
+ Enzyme2  1      38.5 2778.2 68.270
- Enzyme5  1    2216.4 5033.0 70.212
- Enzyme1  1    5478.4 8295.1 75.208

Step:  AIC=64.86
Detox ~ Enzyme1 + Enzyme4 + Enzyme5

          Df Sum of Sq    RSS    AIC
&lt;none&gt;                 2947.1 64.860
+ Enzyme3  1     130.4 2816.7 66.407
+ Enzyme2  1      13.6 2933.4 66.813
- Enzyme4  1    1837.7 4784.8 67.706
- Enzyme5  1    2262.8 5209.8 68.557
- Enzyme1  1    6029.0 8976.1 73.997</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Detox ~ Enzyme1 + Enzyme4 + Enzyme5, data = chap7data2)

Coefficients:
(Intercept)      Enzyme1      Enzyme4      Enzyme5  
  -102.4349       0.1938       0.1008       1.1069  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb622"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb622-1"><a href="#cb622-1" aria-hidden="true" tabindex="-1"></a><span class="co">#or</span></span>
<span id="cb622-2"><a href="#cb622-2" aria-hidden="true" tabindex="-1"></a><span class="fu">allSubsets</span>(chap7data2,<span class="at">y.name=</span><span class="st">"Detox"</span>,<span class="at">perf.measure=</span><span class="st">"mallows.cp"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                             Model      adj.r.squared
1                                  Detox ~ Enzyme5 -0.121740174648695
2                  Detox ~ Enzyme3+Enzyme4+Enzyme5 0.0953356909980044
3                                  Detox ~ Enzyme2  0.121913336927653
4                          Detox ~ Enzyme4+Enzyme5   0.16091426388108
5                  Detox ~ Enzyme2+Enzyme3+Enzyme4  0.220935843219152
6                          Detox ~ Enzyme3+Enzyme5  0.202661735249138
7                          Detox ~ Enzyme3+Enzyme4  0.223753049711396
8                          Detox ~ Enzyme2+Enzyme4  0.255553133684301
9                                  Detox ~ Enzyme4  0.265785404743971
10         Detox ~ Enzyme2+Enzyme3+Enzyme4+Enzyme5  0.374128029592512
11                         Detox ~ Enzyme2+Enzyme3  0.329335344543953
12                                 Detox ~ Enzyme3  0.301375192960427
13 Detox ~ Enzyme1+Enzyme2+Enzyme3+Enzyme4+Enzyme5   0.54551810809289
14                 Detox ~ Enzyme2+Enzyme4+Enzyme5  0.404467243817661
15                 Detox ~ Enzyme1+Enzyme3+Enzyme4  0.451096799223505
16                 Detox ~ Enzyme2+Enzyme3+Enzyme5   0.46270944285908
17                                 Detox ~ Enzyme1  0.384163301765189
18         Detox ~ Enzyme1+Enzyme2+Enzyme4+Enzyme5  0.616094255366656
19         Detox ~ Enzyme1+Enzyme2+Enzyme3+Enzyme4  0.619787416838814
20         Detox ~ Enzyme1+Enzyme2+Enzyme3+Enzyme5  0.627043441524617
21                         Detox ~ Enzyme2+Enzyme5  0.476586035306095
22         Detox ~ Enzyme1+Enzyme3+Enzyme4+Enzyme5  0.631375639659066
23                         Detox ~ Enzyme1+Enzyme3  0.505130867699246
24                         Detox ~ Enzyme1+Enzyme4  0.512984256086067
25                 Detox ~ Enzyme1+Enzyme2+Enzyme5  0.589864494082874
26                         Detox ~ Enzyme1+Enzyme5  0.552720532095238
27                 Detox ~ Enzyme1+Enzyme2+Enzyme4  0.658170511105981
28                 Detox ~ Enzyme1+Enzyme3+Enzyme5  0.668698598042593
29                 Detox ~ Enzyme1+Enzyme4+Enzyme5  0.678591090390398
30                 Detox ~ Enzyme1+Enzyme2+Enzyme3  0.682256480210184
31                         Detox ~ Enzyme1+Enzyme2  0.646870701721216
            r.squared              AIC        perc.error         mallows.cp
1  0.0028976225344936 106.614682983029  0.39431982572297  0.137453882255527
2   0.396890460665336 105.587136855917 0.354116533733155 0.0994323899514434
3   0.219478521713469 104.165771062923 0.348876057988313 0.0945648667123251
4   0.347377760796396 104.376133095174 0.341040255742936 0.0892372756191775
5   0.480623895479435 104.092431403323 0.328616289784617 0.0828508511322706
6   0.379848016304885 103.865794310814 0.332448041968861 0.0828072658700512
7   0.396252371997752 103.597711242751 0.328021590110949 0.0795587491774218
8   0.420985770643346 103.179419011073 0.321232390178822  0.074660851334314
9   0.347364804216863 102.376331624279 0.319017114715357 0.0692398413807154
10  0.652293349773618 102.079740132558 0.294540640692888 0.0688555453531038
11  0.478371934645297 102.135696635339 0.304898428354942 0.0632968017381836
12   0.37900017152038 101.879456538239 0.311189172259715 0.0629751626156955
13  0.798008048041284 98.6484270290975 0.250992513755551               0.06
14  0.602978162545108 101.406061334488 0.287313017352848 0.0586213180485603
15   0.63406453281567 100.590718467776  0.27583562615466 0.0524653558987582
16  0.641806295239386 100.376887629136 0.272902227212976 0.0509322725558538
17  0.452589601569056 100.618136405545 0.292169756597092 0.0484024176453974
18  0.786719030759254 97.1922524896298 0.230682570166493 0.0422355380345724
19  0.788770787132675 97.0955870885837  0.22957030910281 0.0418292334558949
20   0.79280191195812 96.9029013083644 0.227369182566776  0.041030959111525
21  0.592900249682518 99.6567309027967 0.269355054023775 0.0406170238704733
22  0.795208688699481 96.7860631506573 0.226044785017069 0.0405543506688574
23  0.615101785988302 99.0959376823384 0.261907333353099 0.0362205048823659
24   0.62120997695583 98.9359687073529 0.259820836463091 0.0350109139242518
25  0.726576329388583 97.6763734731404 0.238432888587324  0.034145458363074
26  0.652115969407407 98.0848402690308 0.248995763195505 0.0288906715775875
27  0.772113674070654 95.8546178223231  0.21767434129564 0.0251278031069124
28  0.779132398695062 95.5417828096502 0.214296023808806 0.0237379012704586
29  0.785727393593599 95.2386391415135 0.211072391978277 0.0224319096535481
30  0.788170986806789 95.1239425579172 0.209865392142655 0.0219480105299455
31  0.725343879116501 95.7213469375342 0.221242904754148 0.0143895176456604</code></pre>
</div>
</div>
<section id="interpretation-1" class="level2">
<h2 class="anchored" data-anchor-id="interpretation-1">Interpretation 1</h2>
<p>The stepwise regression analysis identified that the best model for predicting <code>Detox</code> includes the variables <code>Enzyme1</code>, <code>Enzyme4</code>, and <code>Enzyme5</code>. This model was chosen because it has the lowest Akaike Information Criterion (AIC) value (64.86), indicating the best balance between model complexity and fit.</p>
<ul>
<li><strong>Enzyme1</strong> and <strong>Enzyme4</strong> have small positive effects on <code>Detox</code>, while <strong>Enzyme5</strong> has a larger positive effect.</li>
<li>The variables <code>Enzyme2</code> and <code>Enzyme3</code> were excluded from the final model as they did not significantly improve the model’s fit.</li>
</ul>
<p>This suggests that <code>Enzyme1</code>, <code>Enzyme4</code>, and <code>Enzyme5</code> are the most important predictors of <code>Detox</code> in this dataset.</p>
</section>
<section id="interpretation-2" class="level2">
<h2 class="anchored" data-anchor-id="interpretation-2">Interpretation 2</h2>
<p>Based on the regression analysis and the adjusted R-squared values for various models, the following conclusions can be drawn:</p>
<ol type="1">
<li><p><strong>Best Model</strong>: The model <code>Detox ~ Enzyme1 + Enzyme2 + Enzyme3</code> has the highest adjusted R-squared value of 0.6823. This indicates that it explains about 68.23% of the variability in <code>Detox</code> and is the best model among all those considered in terms of fit.</p></li>
<li><p><strong>Other Notable Models</strong>:</p>
<ul>
<li>The models <code>Detox ~ Enzyme1 + Enzyme2 + Enzyme5</code> (Adjusted R-squared: 0.6687) and <code>Detox ~ Enzyme1 + Enzyme2 + Enzyme4</code> (Adjusted R-squared: 0.6582) also have high adjusted R-squared values. These models provide a good fit and are close in performance to the best model.</li>
</ul></li>
<li><p><strong>Poorly Performing Models</strong>:</p>
<ul>
<li>Models with adjusted R-squared values close to or below 0, such as <code>Detox ~ Enzyme5</code> (-0.1217) and <code>Detox ~ Enzyme3</code> (0.3014), indicate a poor fit. These models do not explain much of the variability in <code>Detox</code> and are not suitable for prediction.</li>
</ul></li>
<li><p><strong>Model Selection</strong>:</p>
<ul>
<li>The top models to consider for predicting <code>Detox</code> are:
<ul>
<li><code>Detox ~ Enzyme1 + Enzyme2 + Enzyme3</code> (Adjusted R-squared: 0.6823)</li>
<li><code>Detox ~ Enzyme1 + Enzyme2 + Enzyme5</code> (Adjusted R-squared: 0.6687)</li>
<li><code>Detox ~ Enzyme1 + Enzyme2 + Enzyme4</code> (Adjusted R-squared: 0.6582)</li>
</ul></li>
<li>These models provide a good balance between complexity (number of variables) and explanatory power.</li>
</ul></li>
</ol>
<section id="conclusion-1" class="level3">
<h3 class="anchored" data-anchor-id="conclusion-1">Conclusion:</h3>
<p>The best model based on adjusted R-squared is <code>Detox ~ Enzyme1 + Enzyme2 + Enzyme3</code>, which explains 68.23% of the variance in <code>Detox</code>. Models with fewer variables generally have lower adjusted R-squared values and may not provide sufficient explanatory power, while models with negative adjusted R-squared values should be discarded as they do not fit the data well.</p>
</section>
</section>
</section>
<section id="another-example-with-data-3" class="level1">
<h1>Another example with data 3</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb624"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb624-1"><a href="#cb624-1" aria-hidden="true" tabindex="-1"></a>chap7data3.model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y<span class="sc">~</span>.,<span class="at">data=</span>chap7data3)</span>
<span id="cb624-2"><a href="#cb624-2" aria-hidden="true" tabindex="-1"></a><span class="co">#chap7data3.model1 &lt;- lm(Y~X1+X2+X3+X4,data=chap7data3)</span></span>
<span id="cb624-3"><a href="#cb624-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(chap7data3.model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ ., data = chap7data3)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.1750 -1.6709  0.2508  1.3783  3.9254 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)  62.4054    70.0710   0.891   0.3991  
X1            1.5511     0.7448   2.083   0.0708 .
X2            0.5102     0.7238   0.705   0.5009  
X3            0.1019     0.7547   0.135   0.8959  
X4           -0.1441     0.7091  -0.203   0.8441  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.446 on 8 degrees of freedom
Multiple R-squared:  0.9824,    Adjusted R-squared:  0.9736 
F-statistic: 111.5 on 4 and 8 DF,  p-value: 4.756e-07</code></pre>
</div>
<div class="sourceCode cell-code" id="cb626"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb626-1"><a href="#cb626-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(chap7data3.model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       X1        X2        X3        X4 
 38.49621 254.42317  46.86839 282.51286 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb628"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb628-1"><a href="#cb628-1" aria-hidden="true" tabindex="-1"></a>base<span class="sc">::</span><span class="fu">plot</span>(chap7data3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="MLR_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb629"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb629-1"><a href="#cb629-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stepwise</span>(chap7data3.model1, <span class="at">direction=</span><span class="st">'backward'</span>, <span class="at">criterion=</span><span class="st">'AIC'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Direction:  backward
Criterion:  AIC 

Start:  AIC=26.94
Y ~ X1 + X2 + X3 + X4

       Df Sum of Sq    RSS    AIC
- X3    1    0.1091 47.973 24.974
- X4    1    0.2470 48.111 25.011
- X2    1    2.9725 50.836 25.728
&lt;none&gt;              47.864 26.944
- X1    1   25.9509 73.815 30.576

Step:  AIC=24.97
Y ~ X1 + X2 + X4

       Df Sum of Sq    RSS    AIC
&lt;none&gt;               47.97 24.974
- X4    1      9.93  57.90 25.420
- X2    1     26.79  74.76 28.742
- X1    1    820.91 868.88 60.629</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X1 + X2 + X4, data = chap7data3)

Coefficients:
(Intercept)           X1           X2           X4  
    71.6483       1.4519       0.4161      -0.2365  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb632"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb632-1"><a href="#cb632-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stepwise</span>(chap7data3.model1, <span class="at">direction=</span><span class="st">'forward'</span>, <span class="at">criterion=</span><span class="st">'AIC'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Direction:  forward
Criterion:  AIC 

Start:  AIC=71.44
Y ~ 1

       Df Sum of Sq     RSS    AIC
+ X4    1   1831.90  883.87 58.852
+ X2    1   1809.43  906.34 59.178
+ X1    1   1450.08 1265.69 63.519
+ X3    1    776.36 1939.40 69.067
&lt;none&gt;              2715.76 71.444

Step:  AIC=58.85
Y ~ X4

       Df Sum of Sq    RSS    AIC
+ X1    1    809.10  74.76 28.742
+ X3    1    708.13 175.74 39.853
&lt;none&gt;              883.87 58.852
+ X2    1     14.99 868.88 60.629

Step:  AIC=28.74
Y ~ X4 + X1

       Df Sum of Sq    RSS    AIC
+ X2    1    26.789 47.973 24.974
+ X3    1    23.926 50.836 25.728
&lt;none&gt;              74.762 28.742

Step:  AIC=24.97
Y ~ X4 + X1 + X2

       Df Sum of Sq    RSS    AIC
&lt;none&gt;              47.973 24.974
+ X3    1   0.10909 47.864 26.944</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X4 + X1 + X2, data = chap7data3)

Coefficients:
(Intercept)           X4           X1           X2  
    71.6483      -0.2365       1.4519       0.4161  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb635"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb635-1"><a href="#cb635-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stepwise</span>(chap7data3.model1, <span class="at">direction=</span><span class="st">'backward/forward'</span>, <span class="at">criterion=</span><span class="st">'AIC'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Direction:  backward/forward
Criterion:  AIC 

Start:  AIC=26.94
Y ~ X1 + X2 + X3 + X4

       Df Sum of Sq    RSS    AIC
- X3    1    0.1091 47.973 24.974
- X4    1    0.2470 48.111 25.011
- X2    1    2.9725 50.836 25.728
&lt;none&gt;              47.864 26.944
- X1    1   25.9509 73.815 30.576

Step:  AIC=24.97
Y ~ X1 + X2 + X4

       Df Sum of Sq    RSS    AIC
&lt;none&gt;               47.97 24.974
- X4    1      9.93  57.90 25.420
+ X3    1      0.11  47.86 26.944
- X2    1     26.79  74.76 28.742
- X1    1    820.91 868.88 60.629</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X1 + X2 + X4, data = chap7data3)

Coefficients:
(Intercept)           X1           X2           X4  
    71.6483       1.4519       0.4161      -0.2365  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb638"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb638-1"><a href="#cb638-1" aria-hidden="true" tabindex="-1"></a><span class="fu">allSubsets</span>(chap7data3,<span class="at">y.name=</span><span class="st">"Y"</span>,<span class="at">perf.measure=</span><span class="st">"adj.r.squared"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Model     adj.r.squared         r.squared              AIC
1     Y ~ X1+X2+X4 0.976447268267236 0.982335451200427 63.8662854718626
2     Y ~ X1+X2+X3 0.976379572292115 0.982284679219087 63.9035968705951
3     Y ~ X1+X3+X4 0.975041456783125 0.981281092587343 64.6199522325816
4        Y ~ X1+X2 0.974414049442758 0.978678374535632 64.3123927621906
5  Y ~ X1+X2+X3+X4  0.97356343061152  0.98237562040768 65.8366897916517
6        Y ~ X1+X4 0.966965257260317 0.972471047716931 67.6341062672404
7     Y ~ X2+X3+X4 0.963759945848363 0.972819959386272  69.468286610933
8        Y ~ X3+X4 0.922347568738969 0.935289640615807  78.744985808948
9        Y ~ X2+X3 0.816430499370665 0.847025416142221 89.9295421295082
10          Y ~ X4 0.644954869961756 0.674541964131609 97.7440447788562
11          Y ~ X2  0.63592900832723 0.666268257633294 98.0703964203777
12       Y ~ X2+X4  0.61607248954006  0.68006040795005 99.5217275129777
13          Y ~ X1 0.491579662365491 0.533948023835033  102.41187201392
14       Y ~ X1+X3 0.457800098613821 0.548166748844851 104.009080451406
15          Y ~ X3 0.220952070432522 0.285872731229812 107.959804394717
           perc.error         mallows.cp
1  0.0241948282253226 0.0301823347348734
2  0.0242295740305319 0.0304127972306419
3  0.0249064320090681 0.0349682444234851
4  0.0252175376870345 0.0267824159831842
5  0.0256332957861164               0.05
6  0.0286541391065289 0.0549585082475868
7  0.0300120954747619 0.0733747399565644
8  0.0439318436492178  0.223731119646975
9  0.0675463931752181  0.624377163435314
10 0.0939385128212314   1.38730833491677
11  0.095125058915528   1.42486406936961
12 0.0976846931820687   1.38225919754642
13  0.112412176793213    2.0254876912345
14  0.116086473289248   1.98094652569577
15  0.139150249457931   3.15154284140081</code></pre>
</div>
<div class="sourceCode cell-code" id="cb640"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb640-1"><a href="#cb640-1" aria-hidden="true" tabindex="-1"></a>chap7data3.model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> X1 <span class="sc">+</span> X2 <span class="sc">+</span> X4,<span class="at">data=</span>chap7data3)</span>
<span id="cb640-2"><a href="#cb640-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(chap7data3.model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X1 + X2 + X4, data = chap7data3)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.0919 -1.8016  0.2562  1.2818  3.8982 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  71.6483    14.1424   5.066 0.000675 ***
X1            1.4519     0.1170  12.410 5.78e-07 ***
X2            0.4161     0.1856   2.242 0.051687 .  
X4           -0.2365     0.1733  -1.365 0.205395    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.309 on 9 degrees of freedom
Multiple R-squared:  0.9823,    Adjusted R-squared:  0.9764 
F-statistic: 166.8 on 3 and 9 DF,  p-value: 3.323e-08</code></pre>
</div>
<div class="sourceCode cell-code" id="cb642"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb642-1"><a href="#cb642-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(chap7data3.model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      X1       X2       X4 
 1.06633 18.78031 18.94008 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb644"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb644-1"><a href="#cb644-1" aria-hidden="true" tabindex="-1"></a>chap7data3.model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> X1 <span class="sc">+</span> X2,<span class="at">data=</span>chap7data3)</span>
<span id="cb644-2"><a href="#cb644-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(chap7data3.model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X1 + X2, data = chap7data3)

Residuals:
   Min     1Q Median     3Q    Max 
-2.893 -1.574 -1.302  1.363  4.048 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 52.57735    2.28617   23.00 5.46e-10 ***
X1           1.46831    0.12130   12.11 2.69e-07 ***
X2           0.66225    0.04585   14.44 5.03e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.406 on 10 degrees of freedom
Multiple R-squared:  0.9787,    Adjusted R-squared:  0.9744 
F-statistic: 229.5 on 2 and 10 DF,  p-value: 4.407e-09</code></pre>
</div>
<div class="sourceCode cell-code" id="cb646"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb646-1"><a href="#cb646-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(chap7data3.model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      X1       X2 
1.055129 1.055129 </code></pre>
</div>
</div>
<p>#Assess normality</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb648"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb648-1"><a href="#cb648-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(chap7data3.model3<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  chap7data3.model3$residuals
W = 0.90527, p-value = 0.158</code></pre>
</div>
</div>
<p>#Assess homoscedasticity</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb650"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb650-1"><a href="#cb650-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">y=</span>chap7data3.model3<span class="sc">$</span>residuals,<span class="at">x=</span>chap7data3.model3<span class="sc">$</span>fitted.values,<span class="at">main=</span><span class="st">"Residuals vs Yhat"</span>,<span class="at">ylab=</span><span class="st">"residuals"</span>,<span class="at">xlab=</span><span class="st">"Yhat"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="MLR_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="exercises" class="level1">
<h1>Exercises</h1>
<p>Do all the exercices in page 58 on document “Biometry 721/821 Workbook(2024).pdf”</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>