---
title: "MLR"
author: "Cecile Bester"
date: "2024-04-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Required packages

```{r}
library(RcmdrMisc)
library(ggplot2)
library(car)
library(MASS)
```

#the allSubsets() function
```{r}
allSubsets <- function(data,y.name="Y",perf.measure=c("adj.r.squared","r.squared","AIC","perc.error")){
  
  Cols <- names(data)
  Cols <- Cols[! Cols %in% y.name]
  n <- length(Cols)
  
  id <- unlist(
    lapply(1:n,
           function(i)combn(1:n,i,simplify=F)
    )
    ,recursive=F)
  
  Formulas <- sapply(id,function(i)
    paste(y.name,"~",paste(Cols[i],collapse="+"))
  )
  
  result.mat <- matrix(0,nrow=length(Formulas),6)
  result.mat[,1] <- Formulas
  
  #get all adjusted R2 values
  for(i in 1:length(Formulas)){result.mat[i,2] <- summary(lm(as.formula(Formulas[i]),
                                                             data=data))$adj.r.squared}
  #get all R2 values
  for(i in 1:length(Formulas)){result.mat[i,3] <- summary(lm(as.formula(Formulas[i]),
                                                             data=data))$r.squared}
  #get all AIC's
  
  for(i in 1:length(Formulas)){result.mat[i,4] <- AIC(lm(as.formula(Formulas[i]),
                                                         data=data))}
  #get all sigma's
  
  for(i in 1:length(Formulas)){result.mat[i,5] <- summary(lm(as.formula(Formulas[i]),
                                                             data=data))$sigma/mean(data[,y.name])}
  #get all mallows cp's
  
  for(i in 1:length(Formulas)){result.mat[i,6] <- mallows.cp(data=data,model=lm(as.formula(Formulas[i]),
                                                                                data=data),y.name=y.name)}
  
  
  
  colnames(result.mat) <- c("Model","adj.r.squared","r.squared","AIC","perc.error","mallows.cp")
  

  
  final.output <- data.frame(result.mat[order(result.mat[,perf.measure],decreasing=T),])
  
  return(final.output)
  
}

```

#calculating the Mallow's Cp statistic (function) 

```{r}
mallows.cp <- function(data,model,y.name)
{
  
  n <- nrow(data)
  p <- length(model$coefficients)
  
  mean.sq.error <- summary(lm(as.formula(paste(y.name,"~.")),data=data))$sigma^2
  
  sse <- summary(model)$sigma^2*summary(model)$df[2]
  
  cp <- sse/mean.sq.error-(n-2*p)
  cp/100
}

```

#Influence.cutoffs function 

```{r}
influence.cutoffs <- function(model){
  p <- length(model$coefficients)
  n <- length(model$residuals)
  
  DFBETAS <- 2/(n^0.5)
  DFFITS <- 2*(p/n)^0.5
  COVRATIO.lwr <- 1-3*p/n
  COVRATIO.upr <- 1+3*p/n
  cook.D <- 4/n
  HATDIAG <- 2*p/n
  
  list(DFBETAS=DFBETAS,DFFITS=DFFITS,COVRATIO.lwr=COVRATIO.lwr,COVRATIO.upr=COVRATIO.upr,cook.D=cook.D,HATDIAG=HATDIAG)
}


```


#Example 1
#base plotting

```{r}
with(chap7data1,base::plot(Additive,Consumption,col='blue',xlab='Additive',main='Observed data'))
```

#ggplot system

```{r}
chap7data1.plot1 <- ggplot(data=chap7data1,aes(y=Consumption,x=Additive)) 
chap7data1.plot1 + geom_point(size=2) + geom_smooth(method=lm,se=F,formula=y~poly(x,2,raw=T)) + ggtitle("Fuel consumption vs Additive")
```

#Fit possible models

```{r}
chap7data1.model1 <- lm(Consumption ~ Additive, data=chap7data1)
chap7data1.model2 <- lm(Consumption ~ Additive + I(Additive^2), data=chap7data1)
chap7data1.model3 <- lm(Consumption ~ Additive +I(Additive^2)+ I(Additive^3), data=chap7data1)
chap7data1.model4 <- lm(Consumption ~ Additive +I(Additive^2)+ I(Additive^3)+ I(Additive^4), data=chap7data1)
summary(chap7data1.model1)
summary(chap7data1.model2)
summary(chap7data1.model3)
summary(chap7data1.model4)
```

#Check normality

```{r}
shapiro.test(chap7data1.model1$residuals)
shapiro.test(chap7data1.model2$residuals)
shapiro.test(chap7data1.model3$residuals)
```

#check homoscedasticity

```{r}
plot(y=chap7data1.model1$residuals,x=chap7data1$Additive,main="Residuals vs X",ylab="residuals",xlab="X")
plot(y=chap7data1.model2$residuals,x=chap7data1$Additive,main="Residuals vs X",ylab="residuals",xlab="X")
plot(y=chap7data1.model3$residuals,x=chap7data1$Additive,main="Residuals vs X",ylab="residuals",xlab="X")
```


#Influential values

```{r}
rstudent(chap7data1.model3)
influence.measures(chap7data1.model3)
influence.cutoffs(chap7data1.model3)
```

#Example 2

```{r}
chap7data2.model1 <- lm(Detox~.,data=chap7data2)
summary(chap7data2.model1)

base::plot(chap7data2)

stepwise(chap7data2.model1, direction='backward/forward', criterion='AIC')
allSubsets(chap7data2,y.name="Detox",perf.measure="mallows.cp")
```

#Example 3

```{r}
chap7data3.model1 <- lm(Y~.,data=chap7data3)
#chap7data3.model1 <- lm(Y~X1+X2+X3+X4,data=chap7data3)
summary(chap7data3.model1)

vif(chap7data3.model1)

base::plot(chap7data3)

stepwise(chap7data3.model1, direction='backward', criterion='AIC')
stepwise(chap7data3.model1, direction='forward', criterion='AIC')
stepwise(chap7data3.model1, direction='backward/forward', criterion='AIC')

allSubsets(chap7data3,y.name="Y",perf.measure="adj.r.squared")

chap7data3.model2 <- lm(Y ~ X1 + X2 + X4,data=chap7data3)
summary(chap7data3.model2)
vif(chap7data3.model2)

chap7data3.model3 <- lm(Y ~ X1 + X2,data=chap7data3)
summary(chap7data3.model3)
vif(chap7data3.model3)
```

#Assess normality

```{r}
shapiro.test(chap7data3.model3$residuals)
```

#Assess homoscedasticity

```{r}
plot(y=chap7data3.model3$residuals,x=chap7data3.model3$fitted.values,main="Residuals vs Yhat",ylab="residuals",xlab="Yhat")
```

